### ISSUE TITLE
Using "Army: Deactivate script button" causes error in script: attempt too concatenate a nil value

### ISSUE THREAD

**Issue by spacenavy90** [thomascgray/opr-af-to-tts#26]
"When I use the Army: Deactivate script button, it causes ALL of my army's models to become unresponsive (none of the script options work; pinned, activated toggle, etc). It has the attached error."

![image](https://github.com/thomascgray/opr-af-to-tts/assets/10876259/de789550-888a-405f-be59-0542a85652bb)

![image](https://github.com/thomascgray/opr-af-to-tts/assets/10876259/439bc318-d802-430b-b195-8c0a5692e72e)

**Comment by thomascgray** [comment]
Fixed via https://github.com/thomascgray/opr-af-to-tts/releases/tag/1.7.2

Thanks for the bug report!
