### ISSUE TITLE
[Request] Wound tracker for Tough(x) models

### ISSUE THREAD

**Issue by spacenavy90** [thomascgray/opr-af-to-tts#29]
I think a very useful feature to implement in the future would be a wound tracker, similar to what Yellowscribe has.

![image](https://github.com/thomascgray/opr-af-to-tts/assets/10876259/846e21f8-399d-4790-aae6-95aab0b4d627)

https://steamcommunity.com/sharedfiles/filedetails/?id=2920625970
Yellowscribe (Army importer for 40k units) has a similar feature where you can press NUM 2 and 3 to decrease/increase wound count on the model; shown below. 

![image](https://github.com/thomascgray/opr-af-to-tts/assets/10876259/ef4a0f98-49df-4403-af73-1a60379d5ce1)

![image](https://github.com/thomascgray/opr-af-to-tts/assets/10876259/996836a3-7644-4771-ab54-0ce3bd32c56c)

**Comment by thomascgray** [comment]
This is now supported as of https://github.com/thomascgray/opr-af-to-tts/releases/tag/2.0
