### ISSUE TITLE
Eternal Warden Army Failing to Import

### ISSUE THREAD

**Issue by BuzzerPop** [thomascgray/opr-af-to-tts#31]
This is the army being imported: https://army-forge.onepagerules.com/share?id=f_LxS1oZBmEw&name=750_Eternal%20Wardens
This is the resulting opr-af-to-tts link: https://opr-af-to-tts.netlify.app/.netlify/functions/save-list?listId=3x2MKsJpnOcDuPrWXTV6L
The attached image is the error that shows. There's not much else to this issue.
![Tabletop_Simulator_X9TfIqm564](https://github.com/thomascgray/opr-af-to-tts/assets/54551510/5afbbf96-269a-4d11-9f03-9d487a869629)

**Comment by thomascgray** [comment]
Fixed by https://github.com/thomascgray/opr-af-to-tts/releases/tag/1.10
