### ISSUE TITLE
Issue importing sharable link for TTS from Tombola's OPR Army Forge to TTS Tool to OPR AF to TTS Importer TTS mod

### ISSUE THREAD

**Issue by MacDeeps** [thomascgray/opr-af-to-tts#33]
Hello,
I get this error whenever i try to paste a link from the Army Forge to TTS tool into the OPR AF to TTS mod:

Error in script (global): chunk_0:(679, 11-67): Expected string argument to JSON.decode(), got HTML?

![image](https://github.com/thomascgray/opr-af-to-tts/assets/147964245/e79d6753-9214-4822-8346-d3fcee5b0f61)

I've tried completely reinstalling everything, including TTS, from what I can see nothing is blocking TTS in my firewall, I'm still able to join other games. I know I'm copying the correct link because i give it to my partner and they load up a room for me to join and use the link I gave them to load and assign my models.

Not sure what else it could be, I've run out of ideas.

**Comment by thomascgray** [comment]
Hey man, sorry to hear that you're having so much pain with this.

Could you send me all the relevant URLs/IDs? e.g the URL of your army forge link (what you get when you click "Share as link", etc.), an ID from my tool if you still have it, etc.

Will look into this for you and see if I can re-create it!

**Comment by MacDeeps** [comment]
Thanks for getting back to me!

Army Forge list link-
https://army-forge.onepagerules.com/list?listId=1697168316226
Share link-
https://army-forge.onepagerules.com/share?id=Y0hrGPhCMYRP&name=Macrons
Armyforge to TTS tool link-
https://opr-af-to-tts.netlify.app/?fbclid=IwAR3_8zLprgqLJloRIM6khGyZn5IfOnP0g0JN7QnJO7leqTSLne-Zbun9MaI
Shareable link for TTS-
https://opr-af-to-tts.netlify.app/?fbclid=IwAR3_8zLprgqLJloRIM6khGyZn5IfOnP0g0JN7QnJO7leqTSLne-Zbun9MaI.netlify/functions/save-list?listId=hVJg_4SV9ucwU4oIhlVWo

Just tried importing it in TTS again and got the same error message, my
friend was able to do it from his TTS though.

**Comment by thomascgray** [comment]
So I've been trying to recreate this issue and I'm really sorry but I've not been able to have any luck :( 

I put your army forge list into the web tool, generated a new link, pasted that into the mod, and:

![image](https://github.com/thomascgray/opr-af-to-tts/assets/5067968/7050512c-0d7a-44e5-8337-3291c2f97b0b)

Everything seems to work :/

I'm really sorry! I'm going to try and add some more "thorough" error messaging in an upcoming version, so hopefully that might help us track it down.

But for now - you should at least be able to re-generate the shareable link from the webapp, and use that 👍

**Comment by MacDeeps** [comment]
No worries, thanks for the update!
