### ISSUE TITLE
Feature request: have the floating wounds marker optional

### ISSUE THREAD

**Issue by febs** [thomascgray/opr-af-to-tts#34]
Title says it all.
I think it would be cool to have the options _not_ to see those markers, just to leave the wounds count in the model description.

Thanks,

**Comment by thomascgray** [comment]
This is a great shout to be honest - what would you find most useful?

- option to turn them on and off during the web-app/army list building stage?
- or on and off _in game_ through a right click menu item?

Just thinking about the "UI" and what the "ideal" version of this would be.

**Comment by spacenavy90** [comment]
Right click menu option would be my pick

**Comment by febs** [comment]
Hello, thanks for your reply, which I unfortunately missed.

I was thinking about removing them altogether during the building stage actually, but also begin able to enable/disable them on the go could be cool.

Many thanks for caring,
