### ISSUE TITLE
wounds and spell tokens not working to my list.

### ISSUE THREAD

**Issue by 3darkman** [thomascgray/opr-af-to-tts#35]
My army list does not import the Tough information of the units.

https://army-forge.onepagerules.com/share?id=-rpFCVUb&name=Skull_Hunters%20(the%20greatest%20Predators%20in%20the%20galaxy)

**Comment by thomascgray** [comment]
Is this a custom army? Unfortunately, I just can't guarantee things will work for custom armies; theres too many moving parts, and the army forge exported data for custom armies isn't great.

I'll definitely take a look and see if I can spot what's happening though!

Which unit/rule/equipment etc. should be getting/giving Tough and isn't doing?

**Comment by thomascgray** [comment]
OK, I think I got it! Should hopefully be fixed as of https://github.com/thomascgray/opr-af-to-tts/pull/38
