### ISSUE TITLE
Heroes get messed up when attached to a unit.

### ISSUE THREAD

**Issue by Keazra** [thomascgray/opr-af-to-tts#36]
I'm not sure what causes it to happen, but the name/toughness/spellcaster tokens/quality/defense of a hero model tends to get messed up on Tabletop Simulator, if the hero is attached to a unit. The messing up only happens later on and typically not when the model is made. I have a gut feeling that what causes it is modifying the wounds/spellcaster tokens but I haven't delved very deep into this to figure out the precise cause.

**Comment by thomascgray** [comment]
Thanks for this - off the top of my head, I _think_ I know what _might_ be happening. Will hopefully get a chance to look soon. Cheers.

**Comment by thomascgray** [comment]
Got this sorted - the change is just in the Lua code of the mod itself. 

If you look at https://steamcommunity.com/sharedfiles/filedetails/changelog/2969610810 its the "Update: 5 Feb @ 11:50pm" update (not that it has any notes haha)

Let it do a refresh or whatever and all should be good to go.

Thanks again for the bug report!

**Comment by Keazra** [comment]
Dang. You do great work!
