### ISSUE TITLE
Great Death Roller + Bladed Wheels upgrade not displaying correctly.

### ISSUE THREAD

**Issue by Keazra** [thomascgray/opr-af-to-tts#37]
Just a simple bug report; for the Ratmen army in AOF,  the Great Death Roller doesn't display its stats correctly with the Bladed Wheels upgrade, it shows it as having no ranged weapon (correct) but doesn't show the increased impact count nor the bladed wheels trait.

**Comment by thomascgray** [comment]
Thanks for the thorough report, much appreciated 🙏 

Good news: I've re-worked how some upgrades are applied, and I'm hoping its going to catch more bugs "of this nature". 

Bad news: However, I am a _little_ worried that my re-working might be a case of fixing 1 thing Here ™️ and its broken 2 things There ™️  hahaha. So, if you don't mind and if you have a spare 5 mins one evening, could you have a go using your Ratmen list, and also any other things you can think of, against this preview deploy of the webapp specifically https://reworking-upgrade-04-02-2024--opr-af-to-tts.netlify.app/ ? And let me know if you see anything buggy_. And if it all looks good, I'll merge the changes into the main code base.

Interesting to note: Army Forge data around this upgrade is definitely a bit _weird_. The upgrade should give you Bladed Wheels as a weapon, it feels like, but it doesn't?

![image](https://github.com/thomascgray/opr-af-to-tts/assets/5067968/0f896a52-60e7-40f8-a7f8-5a7824568279)

**Comment by Keazra** [comment]
I did the preview build and, while the updated Impact count is now working, it isn't showing the Bladed Wheels ability in the list of abilities.

![image](https://github.com/thomascgray/opr-af-to-tts/assets/38389279/696bafde-605c-4a02-bd3e-ea6b0ddd45a0)

**Comment by thomascgray** [comment]
Thanks for the update - I'll continue tinkering with the preview build. Its basically a question of how far I can push "army forge sometimes gives us weird data so we need to massage back into something sensible" without breaking fundamental things.

**Comment by thomascgray** [comment]
OK, interestingly (putting this here as much as a record for myself as for Keazra);

The special rule text for Bladed Wheels doesn't actually appear anywhere in the TTS endpoint output:

![image](https://github.com/thomascgray/opr-af-to-tts/assets/5067968/b90ca393-d5e5-4f68-a3df-5433da0c96b6)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/5067968/17fb1bd3-4097-4ae2-8306-cb0763887e9a)

So, we can't even really include it anywhere if we wanted to. Very odd. Will speak to the Adam @ Army Forge about it.

**Comment by thomascgray** [comment]
Closing this issue as the adding up of impact, etc. should now be fixed as of https://github.com/thomascgray/opr-af-to-tts/pull/38 and the other stuff around this data item being weird is actually an army forge problem

See https://discord.com/channels/610199287346888743/1204176279373619221 and https://discord.com/channels/610199287346888743/1202359721554612295 for discussion on that.
