### ISSUE TITLE
Unit handling by Datacard

### ISSUE THREAD

**Issue by projape** [thomascgray/opr-af-to-tts#39]
Hi,

might it be possible to include datacards which one could put next to the table and which have the same info as the model description and the same right click menu as the models?

To have an overview of their army next to the table without having to search for all the models.  One could use the select all models function on the card and the unit is easier to spot.

The card could show active/lost models, activation tokens, wounds and fatigue, same as the unit. There could be a "destroyed" function as well, which kinda disables the card.

BR

**Comment by thomascgray** [comment]
Closed because I'm afraid I've got no plans to add something like this (I've done a little bit of investigation and it would be quite a lot of work) and I don't want to give the impression that this will be worked on soon. Sorry!
