### ISSUE TITLE
Combat Bike Upgrade Weapons doesn't get imported properly onto datacards

### ISSUE THREAD

**Issue by Tompa974** [thomascgray/opr-af-to-tts#42]
When upgrading a Dark Master Brother with a Combat Bike Upgrade the Twin Heavy Rifle of the Combat Bike doesn't get imported properly as a weapon. As shown in the image below the import creates a " instead of ' ' which seems to not get imported onto the cards. 
![image](https://github.com/thomascgray/opr-af-to-tts/assets/167704421/4edcb80f-9f47-4942-9f95-0be6ba3bebb5)

**Comment by thomascgray** [comment]
Ah, good spot! No idea how that slipped through the "rip out bad characters" net. Tyty, fixed
