### ISSUE TITLE
Army Special Rules not loaded

### ISSUE THREAD

**Issue by JustNerro** [thomascgray/opr-af-to-tts#44]
Sometimes the full description of an Army Special Rule is not loaded at all, leaving a blank space in the unit description.
No idea to reproduce, it just sometimes happens, and sometimes not.
For example, my DAO union army has some unit's Spotting Laser properly described but some have it blank.

Screenshots:
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/2c8c7109-8a64-4189-bcf6-ea4859df819c)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/88b99eca-9d1d-49d1-a00d-efb379119efb)
![image](https://github.com/thomascgray/opr-af-to-tts/assets/66056323/6ae57bd3-ae92-4d59-8331-fffe62dcbe80)
[Link to the AF list](https://army-forge.onepagerules.com/share?id=XG24Yv8JF2dX&name=Blessed_Sisters%203K).
[Link to the importer list](https://opr-af-to-tts.netlify.app/.netlify/functions/save-list?listId=JLjfLvaqRgBoXauhgrFMl).

**Comment by thomascgray** [comment]
Closed with https://github.com/thomascgray/opr-af-to-tts/pull/45, should hopefully catch it. Lemme know if you spot any more of this bug! tyty for reporting 🙏

**Comment by thomascgray** [comment]
Im not sure what Celestial Sisters are in the screenshot? AF has trouble exporting rules for custom armies though, maybe its that? https://github.com/thomascgray/opr-af-to-tts/issues/25
