### ISSUE TITLE
DAO Union - Spotter: Not printing text correctly for multiple abilities.

### ISSUE THREAD

**Issue by Keazra** [thomascgray/opr-af-to-tts#47]
![image](https://github.com/user-attachments/assets/3eabbb4e-534a-4871-b352-ff9ce47931bd)

Above is the Spotter for the DAO Union, and it's failing to print abilities for the drones it's using, the Spotter Drone and the Inhibitor Drone in particular. The Spotter Drone should grant 2x Spotting Laser's to the unit.

**Comment by Keazra** [comment]
Apparently, there's a rule about not allowing multiple instances of special rules. That said, when I have both of those upgrades, the inhibitor drone upgrade no longer shows.

**Comment by thomascgray** [comment]
![image](https://github.com/user-attachments/assets/00780945-6b22-43d6-800e-14ac3593cdfd)
