### ISSUE TITLE
"Weapon definition missing in Army Forge data" error on weapons in items

### ISSUE THREAD

**Issue by Erfeo-tt** [thomascgray/opr-af-to-tts#50]
Hey,
I seem to be running into a bug on the AF-to-TTS tool. Sometimes it gives error on weapons that came attached to an item (e.g. mount) upgrade. However, it doesn't happen every time. I have only had it happen in lists for Regiments, but I'm not sure if it's limited to that, as I don't know how to replicate the bug on purpose (either in Regiments or in other games).

Here is an example:
https://army-forge.onepagerules.com/share?id=QPjYdItM5veX&name=Test_tombola
When I put this army into the tool, the first unit+hero works correctly. However on the second unit the "Heavy Bite" weapon that came with the wolf mounts are displaying an error, for both the models in the unit and the attached hero. This is a copy of a real list that I made with all the other units deleted for the sake of the example.

Here is another example of a full list:
https://army-forge.onepagerules.com/share?id=WuIO2sRoGXqI&name=Ratmen
Unit #15, Battle Master on Great Beast has the same error on the Beasts "Rending Claws"

PS, I know you're not spending as much time on the tool anymore, but would it still be useful to make suggestions for UI adjustments, new features here?

**Comment by thomascgray** [comment]
"Weapon definition missing in Army Forge data" is unfortunately as it sounds; its the error that the tool gives when some of the exported data is referencing something that Army Forge hasn't supplied. Honestly, your best bet is to keep a reference as to what causes the error, then letting Adam at Army Forge know.

Thanks for the issue though; I'll look into improving the error message maybe? So you can at least keep better track of what is happening.

And yep, I haven't played OPR in a long while; but absolutely! I'm happy to receive suggestions for new UI/features here on github and I'll absolutely look into them time permitting 👍

**Comment by thomascgray** [comment]
Finally got a chance to look at this tonight: managed to get a work around going! Some bad code on my part, and some missing data in Army Forge, but we're doing some mad fallbacks and getting there in the end:
![image](https://github.com/user-attachments/assets/8311d6ce-163b-409f-b012-c531abb58c3c)

**Comment by thomascgray** [comment]
OK, fix deployed, closing this issue. Thanks again!
